CREATE DATABASE IF NOT EXISTS `database_champs`;
USE database_champs;


DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS programming;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS users;



CREATE TABLE `users` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(150) NOT NULL,
    `surname` VARCHAR(150) NOT NULL,
    `role` VARCHAR(150) NOT NULL DEFAULT 'Cliente' COMMENT 'Cliente/Administrador',
    `avatar` VARCHAR(150) NULL,
    `email` VARCHAR(150) NOT NULL,
    `password` VARCHAR(180) NOT NULL,
    `status` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'A/I -> Activo/Inactivo',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `delete_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY users_unique_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `countries` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `prefix` VARCHAR(180) NOT NULL,
    `country` VARCHAR(180) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `delete_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY countries_unique_prefix (prefix)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `teams` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `prefix` VARCHAR(180) NOT NULL,
    `country_name` VARCHAR(180) NOT NULL,
    `photo_shield` VARCHAR(180) DEFAULT NULL,
    `photo_flag` VARCHAR(180) DEFAULT NULL,
    `photo_team` VARCHAR(180) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `delete_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY teams_unique_prefix (prefix),
    UNIQUE KEY teams_unique_cn (country_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `players` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `team_id` BIGINT(20) UNSIGNED NOT NULL,
    `name` VARCHAR(150) NOT NULL,
    `surname` VARCHAR(150) NOT NULL,
    `nationality` VARCHAR(150) NOT NULL,
    `birth` DATE DEFAULT NULL COMMENT 'Nacimiento',
    `team_position` VARCHAR(150) NOT NULL,
    `team_number` INT(11) NOT NULL DEFAULT 0,
    `photo_player` VARCHAR(180) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `delete_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `groups` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `group` CHAR(1) NOT NULL,
    `position` INT(11) NOT NULL,
    `team_id` BIGINT(20) UNSIGNED NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `delete_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY groups_unique_team (team_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `programming` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `date` DATE DEFAULT NULL COMMENT 'Fecha juego',
    `new_group` VARCHAR(150) NOT NULL,
    `phase` VARCHAR(150) NOT NULL,
    `description` VARCHAR(150) NOT NULL,
    `first_team_id` BIGINT(20) UNSIGNED NOT NULL,
    `firts_team_marker` INT(11) NOT NULL DEFAULT 0,
    `second_team_id` BIGINT(20) UNSIGNED NOT NULL,
    `second_team_marker` INT(11) NOT NULL DEFAULT 0,
    `status_play` CHAR(3) NOT NULL DEFAULT 'OFF' COMMENT 'ON/OFF',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `delete_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `cards` (
    `game_id` BIGINT(20) UNSIGNED NOT NULL COMMENT 'foranea programming',
    `team_id` BIGINT(20) UNSIGNED NOT NULL,
    `player_id` BIGINT(20) UNSIGNED NOT NULL,
    `color` CHAR(1) NOT NULL COMMENT 'Y:yellow/R:red',
    UNIQUE KEY groups_unique_game (game_id, team_id, player_id, color)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



ALTER TABLE players ADD KEY fk_players_teams (team_id);
ALTER TABLE players ADD CONSTRAINT fk_players_teams 
    FOREIGN KEY (team_id) 
    REFERENCES teams (id) 
    ON UPDATE RESTRICT 
    ON DELETE CASCADE;



/* 
user = "alfonso@ejemplo.com"
password = "admin12345"
*/
INSERT INTO `users` (`name`, `surname`, `role`, `avatar`, `email`, `password`) VALUES
('Alfonso', 'Chávez Baquero', 'Administrador', 'achb.png', 'demo@ejemplo.com', '7488e331b8b64e5794da3fa4eb10ad5d');


INSERT INTO `countries` (`id`, `prefix`, `country`) VALUES
    (NULL, 'af', 'Afganistán'),
    (NULL, 'ax', 'Åland '),
    (NULL, 'al', 'Albania'),
    (NULL, 'de', 'Alemania'),
    (NULL, 'ad', 'Andorra'),
    (NULL, 'ao', 'Angola'),
    (NULL, 'ai', 'Anguila'),
    (NULL, 'aq', 'Antártida'),
    (NULL, 'sa', 'Arabia Saudita'),
    (NULL, 'dz', 'Argelia'),
    (NULL, 'ar', 'Argentina'),
    (NULL, 'au', 'Australia'),
    (NULL, 'at', 'Austria'),
    (NULL, 'az', 'Azerbaiyán'),
    (NULL, 'bs', 'Bahamas'),
    (NULL, 'bd', 'Bangladesh'),
    (NULL, 'bb', 'Barbados'),
    (NULL, 'bh', 'Baréin'),
    (NULL, 'be', 'Bélgica'),
    (NULL, 'bz', 'Belice'),
    (NULL, 'bj', 'Benín '),
    (NULL, 'bm', 'Bermudas'),
    (NULL, 'by', 'Bielorrusia'),
    (NULL, 'bo', 'Bolivia'),
    (NULL, 'ba', 'Bosnia y Herzegovina'),
    (NULL, 'bw', 'Botsuana'),
    (NULL, 'br', 'Brasil'),
    (NULL, 'bn', 'Brunéi'),
    (NULL, 'bg', 'Bulgaria'),
    (NULL, 'bf', 'Burkina Faso'),
    (NULL, 'bi', 'Burundi'),
    (NULL, 'bt', 'Bután '),
    (NULL, 'cv', 'Cabo Verde'),
    (NULL, 'kh', 'Camboya'),
    (NULL, 'cm', 'Camerún'),
    (NULL, 'ca', 'Canadá'),
    (NULL, 'qa', 'Catar '),
    (NULL, 'td', 'Chad'),
    (NULL, 'cl', 'Chile '),
    (NULL, 'cn', 'China '),
    (NULL, 'cy', 'Chipre'),
    (NULL, 'va', 'Ciudad del Vaticano'),
    (NULL, 'co', 'Colombia'),
    (NULL, 'km', 'Comoras'),
    (NULL, 'cg', 'Congo '),
    (NULL, 'kp', 'Corea del Norte'),
    (NULL, 'kr', 'Corea del Sur '),
    (NULL, 'ci', 'Costa de Marfil'),
    (NULL, 'cr', 'Costa Rica'),
    (NULL, 'hr', 'Croacia'),
    (NULL, 'cu', 'Cuba'),
    (NULL, 'cw', 'Curazao'),
    (NULL, 'dk', 'Dinamarca '),
    (NULL, 'dm', 'Dominica'),
    (NULL, 'ec', 'Ecuador'),
    (NULL, 'eg', 'Egipto'),
    (NULL, 'sv', 'El Salvador'),
    (NULL, 'ae', 'Emiratos Árabes Unidos'),
    (NULL, 'er', 'Eritrea'),
    (NULL, 'gb-sct', 'Escocia'),
    (NULL, 'sk', 'Eslovaquia'),
    (NULL, 'si', 'Eslovenia '),
    (NULL, 'es', 'España'),
    (NULL, 'us', 'Estados Unidos'),
    (NULL, 'ee', 'Estonia'),
    (NULL, 'et', 'Etiopía'),
    (NULL, 'ph', 'Filipinas '),
    (NULL, 'fi', 'Finlandia '),
    (NULL, 'fj', 'Fiyi'),
    (NULL, 'fr', 'Francia'),
    (NULL, 'ga', 'Gabón '),
    (NULL, 'gb-wls', 'Gales '),
    (NULL, 'gm', 'Gambia'),
    (NULL, 'gh', 'Ghana '),
    (NULL, 'gi', 'Gibraltar '),
    (NULL, 'gd', 'Granada'),
    (NULL, 'gr', 'Grecia'),
    (NULL, 'gl', 'Groenlandia'),
    (NULL, 'gp', 'Guadalupe '),
    (NULL, 'gu', 'Guam'),
    (NULL, 'gt', 'Guatemala '),
    (NULL, 'gg', 'Guernsey'),
    (NULL, 'gn', 'Guinea'),
    (NULL, 'gy', 'Guyana'),
    (NULL, 'ht', 'Haití'),
    (NULL, 'hn', 'Honduras'),
    (NULL, 'hk', 'Hong Kong '),
    (NULL, 'hu', 'Hungría'),
    (NULL, 'in', 'India '),
    (NULL, 'id', 'Indonesia'),
    (NULL, 'gb-eng', 'Inglaterra'),
    (NULL, 'iq', 'Irak'),
    (NULL, 'ir', 'Irán'),
    (NULL, 'ie', 'Irlanda'),
    (NULL, 'bv', 'Isla Bouvet'),
    (NULL, 'im', 'Isla de Man'),
    (NULL, 'cx', 'Isla de Navidad'),
    (NULL, 'nf', 'Isla Norfolk'),
    (NULL, 'is', 'Islandia'),
    (NULL, 'il', 'Israel'),
    (NULL, 'it', 'Italia'),
    (NULL, 'jm', 'Jamaica'),
    (NULL, 'jp', 'Japón '),
    (NULL, 'je', 'Jersey'),
    (NULL, 'jo', 'Jordania'),
    (NULL, 'kz', 'Kazajistán'),
    (NULL, 'ke', 'Kenia '),
    (NULL, 'kg', 'Kirguistán'),
    (NULL, 'ki', 'Kiribati'),
    (NULL, 'xk', 'Kosovo'),
    (NULL, 'kw', 'Kuwait'),
    (NULL, 'la', 'Laos'),
    (NULL, 'ls', 'Lesoto'),
    (NULL, 'lv', 'Letonia'),
    (NULL, 'lb', 'Líbano'),
    (NULL, 'lr', 'Liberia'),
    (NULL, 'ly', 'Libia '),
    (NULL, 'li', 'Liechtenstein'),
    (NULL, 'lt', 'Lituania'),
    (NULL, 'lu', 'Luxemburgo'),
    (NULL, 'mo', 'Macao '),
    (NULL, 'mk', 'Macedonia del Norte'),
    (NULL, 'mg', 'Madagascar'),
    (NULL, 'my', 'Malasia'),
    (NULL, 'mw', 'Malawi'),
    (NULL, 'mv', 'Maldivas'),
    (NULL, 'ml', 'Malí'),
    (NULL, 'mt', 'Malta'),
    (NULL, 'ma', 'Marruecos'),
    (NULL, 'mq', 'Martinica'),
    (NULL, 'mu', 'Mauricio'),
    (NULL, 'mr', 'Mauritania'),
    (NULL, 'yt', 'Mayotte'),
    (NULL, 'mx', 'México'),
    (NULL, 'fm', 'Micronesia'),
    (NULL, 'md', 'Moldavia'),
    (NULL, 'mc', 'Mónaco'),
    (NULL, 'mn', 'Mongolia'),
    (NULL, 'me', 'Montenegro'),
    (NULL, 'ms', 'Montserrat'),
    (NULL, 'mz', 'Mozambique'),
    (NULL, 'mm', 'Myanmar'),
    (NULL, 'na', 'Namibia'),
    (NULL, 'nr', 'Nauru'),
    (NULL, 'np', 'Nepal '),
    (NULL, 'ni', 'Nicaragua '),
    (NULL, 'ne', 'Níger '),
    (NULL, 'ng', 'Nigeria'),
    (NULL, 'nu', 'Niue'),
    (NULL, 'no', 'Noruega'),
    (NULL, 'nc', 'Nueva Caledonia'),
    (NULL, 'nz', 'Nueva Zelanda'),
    (NULL, 'om', 'Omán'),
    (NULL, 'nl', 'Países Bajos'),
    (NULL, 'pk', 'Pakistán'),
    (NULL, 'pw', 'Palaos'),
    (NULL, 'ps', 'Palestina'),
    (NULL, 'pa', 'Panamá'),
    (NULL, 'pg', 'Papúa Nueva Guinea'),
    (NULL, 'py', 'Paraguay'),
    (NULL, 'pe', 'Perú'),
    (NULL, 'pf', 'Polinesia Francesa'),
    (NULL, 'pl', 'Polonia'),
    (NULL, 'pt', 'Portugal'),
    (NULL, 'pr', 'Puerto Rico'),
    (NULL, 'gb', 'Reino Unido'),
    (NULL, 'cf', 'República Centroafricana'),
    (NULL, 'cz', 'República Checa'),
    (NULL, 'do', 'República Dominicana'),
    (NULL, 'rw', 'Ruanda'),
    (NULL, 'ro', 'Rumania'),
    (NULL, 'ru', 'Rusia '),
    (NULL, 'eh', 'Sahara Occidental'),
    (NULL, 'ws', 'Samoa '),
    (NULL, 'as', 'Samoa Americana'),
    (NULL, 'bl', 'San Bartolomé '),
    (NULL, 'kn', 'San Cristóbal y Nieves'),
    (NULL, 'sm', 'San Marino'),
    (NULL, 'sn', 'Senegal'),
    (NULL, 'rs', 'Serbia'),
    (NULL, 'sc', 'Seychelles'),
    (NULL, 'sl', 'Sierra Leona'),
    (NULL, 'sg', 'Singapur'),
    (NULL, 'sy', 'Siria '),
    (NULL, 'so', 'Somalia'),
    (NULL, 'lk', 'Sri Lanka '),
    (NULL, 'sz', 'Suazilandia'),
    (NULL, 'za', 'Sudáfrica '),
    (NULL, 'sd', 'Sudán'),
    (NULL, 'ss', 'Sudán del Sur '),
    (NULL, 'se', 'Suecia'),
    (NULL, 'ch', 'Suiza'),
    (NULL, 'sr', 'Surinam'),
    (NULL, 'sj', 'Svalbard y Jan Mayen'),
    (NULL, 'th', 'Tailandia '),
    (NULL, 'tw', 'Taiwán'),
    (NULL, 'tz', 'Tanzania'),
    (NULL, 'tj', 'Tayikistán'),
    (NULL, 'tl', 'Timor Oriental'),
    (NULL, 'tg', 'Togo'),
    (NULL, 'tk', 'Tokelau'),
    (NULL, 'to', 'Tonga '),
    (NULL, 'tt', 'Trinidad y Tobago '),
    (NULL, 'tn', 'Túnez '),
    (NULL, 'tm', 'Turkmenistán'),
    (NULL, 'tr', 'Turquía'),
    (NULL, 'tv', 'Tuvalu'),
    (NULL, 'ua', 'Ucrania'),
    (NULL, 'ug', 'Uganda'),
    (NULL, 'uy', 'Uruguay'),
    (NULL, 'uz', 'Uzbekistán'),
    (NULL, 'vu', 'Vanuatu'),
    (NULL, 've', 'Venezuela '),
    (NULL, 'vn', 'Vietnam'),
    (NULL, 'wf', 'Wallis y Futuna'),
    (NULL, 'ye', 'Yemen'),
    (NULL, 'dj', 'Yibuti'),
    (NULL, 'zm', 'Zambia'),
    (NULL, 'zw', 'Zimbabue');